### ISSUE TITLE
DK zone: Portal

### ISSUE THREAD

**Issue by Starzu** [SkyFireArchives/SkyFireDB#49]
At map 0 in DK zone portal in Acherus doesn't work. Any idea how to fix it?

**Comment by Raydeon** [comment]
Is this the portal that takes you between floors?

**Comment by Starzu** [comment]
Yes. On map 609 it works.

**Comment by Raydeon** [comment]
Sorry, I have not had much time to look at this issue yet... but I do plan on having it fixed sometime this week.

Raydeon

**Comment by Starzu** [comment]
If you have .gm on it works fine.

**Comment by Raydeon** [comment]
at what point does the map switch to map 0? I just completed most of the quests in the dk area, and every time I return to this area, it is always map 609.

**Comment by Starzu** [comment]
It's when you learn Death Gate. It should return you to map 0, not 609.

**Comment by Raydeon** [comment]
Ok, which database are you using? I ask because I finally got around to checking this, and it worked perfectly fine. I tried with two different characters, in both gm mode and normal, and they worked in both modes. I have, however, fixed the gameobject for the purple visual for the portals though. That will be released in the next patch.

**Comment by Starzu** [comment]
It's problem in 256 phase. You should change phaseMask for them too.
